woowahan-techcamp/6team_waiting

web/.gitignore, web/README.md, web/index.html, web/package-lock.json, web/package.json, web/src/index.css, web/src/index.js, web/src/util.js, web/webpack.config.js
#1 과 관련된 이슈 입니다. 
테스트 세팅을 제외하고 웹팩, 바벨, dev-server, css-loader 설치를 완료했습니다.
=> [이슈#1] 웹 프로젝트 세팅

web/package-lock.json, web/package.json, web/src/index.js
#5 와 관련된 이슈 입니다.
Firebase 권한 메일로 전송하고 웹은 연동 시켰습니다.
=> [이슈#5] 웹 Firebase 세팅

web_baemin_waiting/src/model/user.model.js
=> [이슈#18] User 모델링

web_baemin_waiting/src/index.js, web_baemin_waiting/src/model/user.model.js, web_baemin_waiting/src/services/service.js
#7 
getCurrentUid 로 현재 로그인되어 있는 user 의 uid 를 가져 올 수 있습니다.
isAuthenticated 로 현재 로그인 되어 있는 상태 인지 확인할 수 있습니다. 
saveUserData 로 firebase DB 에 user 의 회원정보를 저장합니다.
firebase DB 에 sample data 를 삽입해봤으니, 확인 부탁드립니다!
=> [이슈#7] Auth 관련 기능 구현

web_baemin_waiting/src/model/store.model.js
=> [이슈#18] Store 객체 모델링

web_baemin_waiting/src/index.js, web_baemin_waiting/src/model/store.model.js, web_baemin_waiting/src/services/service.js
#7 
**getUserByUid** : uid 로 해당 user 의 data 를 가져오는 함수입니다. 
비동기로 진행되어 promise 패턴을 활용해 구현하였습니다. 
**registerStore**: store 객체를 저장합니다.
=> [이슈#7] 레스토랑 등록 외 기능 구현

web_baemin_waiting/src/model/waitingTicket.model.js
=> [이슈#18] WaitingTicket 객체 모델링

web_baemin_waiting/src/index.js, web_baemin_waiting/src/js/util.js
#56 
html이 성공적으로 렌더링 된 후에 진행되어야할 작업 처리를 위해 setTemplateInHtml 함수에 Promise 패턴을 적용했습니다.
=> [이슈#56] setTemplateInHtml 함수에 Promise 패턴 적용

web_baemin_waiting/src/index.js, web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/templates/manage.handlebars, web_baemin_waiting/src/js/templates/my-page.handlebars, web_baemin_waiting/src/js/templates/register.handlebars, web_baemin_waiting/src/js/templates/templates.js, web_baemin_waiting/src/style/no-store.css, web_baemin_waiting/src/style/no-store.scss
#29 
navigator 클릭시 클릭된 navi 에 따라 템플릿이 홈 board 에 삽입됩니다.
=> [이슈#29] 홈 화면의 board 에 페이지 삽입

web_baemin_waiting/src/index.js, web_baemin_waiting/src/js/templates/register.handlebars, web_baemin_waiting/src/js/templates/templates.js, web_baemin_waiting/src/style/register.css, web_baemin_waiting/src/style/register.scss
#29 
가게등록 페이지 html, css 구현입니다. 
아직 정확한 데이터 형태가 나오지 않아서 기본 form 만 작성했습니다.
=> [이슈#29] register 페이지

web_baemin_waiting/src/index.js, web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/templates/my-page-auth.handlebars, web_baemin_waiting/src/js/templates/my-page.handlebars, web_baemin_waiting/src/js/templates/templates.js, web_baemin_waiting/src/js/util.js, web_baemin_waiting/src/style/my-page.css, web_baemin_waiting/src/style/my-page.scss
=> [이슈#29] 마이페이지 html, css

web_baemin_waiting/src/js/templates/manage.handlebars, web_baemin_waiting/src/js/templates/templates.js
#69 
고객관리 리스트 HTML 템플릿에서 아직 데이터를 받아오기 전이라 each 문을 삭제했습니다.
=> [이슈#69] 고객 관리 리스트

web_baemin_waiting/src/index.js, web_baemin_waiting/src/js/home-navigator.js
HomeNavigator class 내의 function 정리
=> HomeNavigator function 리팩토링

web_baemin_waiting/src/index.js, web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/menu.js, web_baemin_waiting/src/style.js
index.js, home-navigator.js 내 코드들을 정리했습니다.
변경되거나 추가된 기능은 없습니다.
=> index.js 및 home-navigator.js 정리

web_baemin_waiting/src/js/home-navigator.js
#76 
마이페이지에 접속할 때 등록된 가게가 없을 경우, 
내 가게를 표시하는 html 이 화면상에 표시되지 않습니다.
=> [이슈#76] 마이페이지 등록된 가게가 없을경우

web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/services/service.js, web_baemin_waiting/src/js/templates/my-info.handlebars, web_baemin_waiting/src/js/templates/templates.js, web_baemin_waiting/src/style/my-page.css, web_baemin_waiting/src/style/my-page.scss
#76 
마이페이지에 접속시 본인이 등록했던 메뉴가 화면에 표시됩니다.
=> [이슈#76] 마이페이지내 본인 가게 메뉴 표시

web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/view.js
HomeNavigator 클래스에서 DOM css style 조작과 관련된 함수를 View class 로 분리했습니다.
=> CSS class 관련 함수 분리

ios_baemin_waiting/ios_baemin_waiting/Controller/CheckTicketViewController.swift, ios_baemin_waiting/ios_baemin_waiting/Controller/DetailViewController.swift, ios_baemin_waiting/ios_baemin_waiting/Controller/WaitingTicketViewController.swift, ios_baemin_waiting/ios_baemin_waiting/Helper/Constant.swift, ios_baemin_waiting/ios_baemin_waiting/Helper/ServerRepository.swift, ios_baemin_waiting/ios_baemin_waiting/Model/WaitingTicket.swift, ios_baemin_waiting/ios_baemin_waiting/View/Detail/StoreDetailView.storyboard, ios_baemin_waiting/ios_baemin_waiting/View/Waiting/Waiting.storyboard
=> ticket create

ios_baemin_waiting/ios_baemin_waiting/Controller/CheckTicketViewController.swift, ios_baemin_waiting/ios_baemin_waiting/Controller/WaitingTicketViewController.swift, ios_baemin_waiting/ios_baemin_waiting/Helper/Constant.swift, ios_baemin_waiting/ios_baemin_waiting/Helper/ServerRepository.swift, ios_baemin_waiting/ios_baemin_waiting/Model/WaitingTicket.swift
=> checking page success

ios_baemin_waiting/ios_baemin_waiting/Controller/MapViewController+CollectionViewDelegate.swift, ios_baemin_waiting/ios_baemin_waiting/Helper/ServerRepository.swift, ios_baemin_waiting/ios_baemin_waiting/Model/Store.swift, ios_baemin_waiting/ios_baemin_waiting/View/Main/MainMapCollectionViewCell.swift, ios_baemin_waiting/ios_baemin_waiting/View/Main/MainMapCollectionViewCell.xib
이슈 #132 
일부 작동하지 않던 카드 스와이프 문제 수정
=> Map error debug

web_baemin_waiting/src/js/auth.js, web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/manage.js, web_baemin_waiting/src/js/model/status.model.js, web_baemin_waiting/src/js/model/token.model.js, web_baemin_waiting/src/js/services/service.js, web_baemin_waiting/src/js/templates/my-info.handlebars, web_baemin_waiting/src/js/templates/templates.js, web_baemin_waiting/src/style/waiting-style.css
=> 가게 수정페이지, 로그아웃 처리 

ios_baemin_waiting/ios_baemin_waiting/Controller/MainContainerViewController.swift, ios_baemin_waiting/ios_baemin_waiting/Helper/Constant.swift, ios_baemin_waiting/ios_baemin_waiting/View/Main/Main.storyboard
이슈 
#155
#145  
내용
myticket 세팅
delete error 수정
=> Set myticket page

web_baemin_waiting/.firebaserc, web_baemin_waiting/firebase.json, web_baemin_waiting/index.html, web_baemin_waiting/src/js/auth.js, web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/manage.js, web_baemin_waiting/src/js/map.js, web_baemin_waiting/src/js/services/service.js
=> 데모 테스트 후 버그수정

web_baemin_waiting/src/js/auth.js, web_baemin_waiting/src/js/home-navigator.js
가게가 오픈되어 있는 상태에서 로그아웃을 하면, 
확인 메세지를 화면에 표시
=> 로그아웃 시 확인 메세지 표시

web_baemin_waiting/src/js/auth.js, web_baemin_waiting/src/js/home-navigator.js
가게 등록 후 발생하는 로직에 대해 함수로 따로 분리하였습니다.
=> 가게 등록 후 로직

web_baemin_waiting/src/js/home-navigator.js, web_baemin_waiting/src/js/services/service.js, web_baemin_waiting/src/js/util.js
=> [#이슈] 티켓 버튼 수정
